---
title: "Donate"
---

<form action="https://actieplatform.ugent.be/en-GB/p/lavaan-project/step-1" method="get" target="_blank"><button class="btn btn-outline-warning" type="submit">DONATE for lavaan</button></form>

### **lavaan is free**

The lavaan package is free (as in beer) and open-source. We very much plan to
keep it that way. But the [bus
factor](https://en.wikipedia.org/wiki/Bus_factor) of the lavaan project is
(currently) one, and the main developer (Yves Rosseel) finds it increasingly
more difficult to find time to maintain (let alone further develop) lavaan.

At the same time, the user base of lavaan is expanding rapidly, and lavaan has
become 'critical software' in many research domains.

This situation is inherently unsustainable, and we are looking for ways to hire
more staff to support the lavaan project. One avenue is to ask for donations.

### **Donations**

From 1 July 2023 onwards, it is possible to donate money to the lavaan project.
The money will go to [Ghent University](https://www.ugent.be/schenken/en), and
will be used exclusively to hire qualified staff (at the post-doc level) that
will support the lavaan project.
Our initial goal is to raise about 120,000 euro (the gross salary of a post-doc in Flanders) to hire a qualified person for 1 full year (hopefully, starting in 2024). This person will assist the main developer to:

1.  create high-quality documentation for users,
2.  create detailed technical documentation (matching the code), and
3.  create a public cloud-based quality-testing platform to ensure the correctness of the lavaan output (in particular after a new update).
4.  add new features to lavaan (see plans below)

### **Plans for lavaan**

Our long-term goals are:

- greater functionality
- to get (most of) the features of LISREL/Mplus/gllamm in lavaan (and more)
- to improve the user-facing documentation
- to improve the internal technical codebase documentation
- having a cloud-based test suite to ensure lavaan is as accurate as possible
- to grow an open source community of contributors
- faster model estimation
- more modularity and better connectivity with other software
- other UX improvements

In the medium term:

- better support for models with NO latent variables
- full support for non-iterative estimators, including James-Stein type 
shrinkage estimators
- outlier-robust estimation approaches
- improved small sample inference
- multilevel SEM with categorical data (using adaptive quadrature)
- support for discrete latent variables (aka mixture modeling, latent class analysis)

More concretely, here are some future updates you can expect in the 0.6 series:

- EFA for many groups (including alignment procedures and rotation methods
that seek agreement across groups)
- two-level SEM with random slopes
- random starts
- faster EM estimation for multilevel SEM
- further extensions of the structural after measurement (SAM) approach (including support for latent interactions)

If any of these sound like things you'd be interested in helping out with, head
to the [Github repository](https://github.com/yrosseel/lavaan), and create a
pull request or a new issue. If you just want to see them in lavaan, click on
the donate button below.

### **How to make a donation**

Donations can be made using the following link (note: you will be redirected to the domain actieplatform.ugent.be):

<form action="https://actieplatform.ugent.be/en-GB/p/lavaan-project/step-1" method="get" target="_blank"><button class="btn btn-outline-warning" type="submit">DONATE for lavaan</button></form><br>

The following payment methods are available: Bancontact, VISA, iDEAL, 
Maestro, Mastercard, Belfius Pay Button, KBC/CBC Pay Button.

If you prefer using a bank transfer, please use the following details:

-   Beneficiary: UNIVERSITEIT GENT
-   IBAN: BE26 3900 9658 0329 (remove spaces if necessary)
-   Swift code (BIC): BBRUBEBB
-   Bank reference: FWUGENTPP1226

For more information about the donation process, tax certificates, etcetera,
please contact the friendly people of the [University
Fund](https://www.ugent.be/schenken/en/contact) of Ghent University.


### Research project/grant money 

If you have received a research project grant and are currently utilizing
lavaan in your research, we kindly request that you contemplate contributing a
financial contribution to support the lavaan project.

Please be aware that most funding agencies do not permit the use of project
funds for donations. Nevertheless, you have the option to make a voluntary
payment for 'lavaan support,' and we can provide you with an official invoice
upon request. To proceed with this, kindly get in touch with
Isabelle Saelens (email: Isabelle.Saelens@UGent.be), who will provide
you with additional guidance.
